### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by JoshTheBlack** [flathub/gg.guilded.Guilded#16]
Unable to install via flatpak due to the following error:

`Failed to install gg.guilded.Guilded: Wrong size for extra data https://www.guilded.gg/downloads/Guilded-Linux.deb`

**Comment by losuler** [comment]
I'm sorry about that, I missed the open pull request https://github.com/flathub/gg.guilded.Guilded/pull/15 for the new version.

I've merged it now https://github.com/flathub/gg.guilded.Guilded/commit/9e30361d17dc3d0e1c9f8afb3f933f0536b7f273 and it should be up shortly.

**Comment by danDDv77** [comment]
Same error at today, 9 september 2024 (2 years later?) :  

**error: Fallo al instalar gg.guilded.Guilded: Tamaño incorrecto en los datos adicionales https://www.guilded.gg/downloads/Guilded-Linux.deb**
