### ISSUE TITLE
Random freeze/crash after some time in a call

### ISSUE THREAD

**Issue by LegitGreenBoi** [flathub/gg.guilded.Guilded#23]
After being in a voice call for about an hour the client will sometimes fully lock up requiring the user to fully close and relaunch the program to fix it. This has been happening to me and a buddy of mine as well, both of us running Flatpak Guilded. Not sure if it's an upstream Guilded issue or a flatpak problem.

**Comment by pogman9000** [comment]
I'm not particularly sure if this is the same rooted issue, but all of my buddy's are having like a weird memory leak issue with guilded right now. Check your ram usage after some time of using the application and see if it's an issue. I've been using the browser and I have no problems.

**Comment by LegitGreenBoi** [comment]
This hasn't been happening to me or my buddy anymore. This issue can probably be closed unless anyone else is still having it.
