### ISSUE TITLE
Flathub wrong size for extra data issue again. 

### ISSUE THREAD

**Issue by pogman9000** [flathub/gg.guilded.Guilded#26]
error: Failed to install gg.guilded.Guilded: Wrong size for extra data https://www.guilded.gg/downloads/Guilded-Linux.deb

I don't ever post these issues usually, but it seems the last issue like this hasn't been for a while so I figured I'd post it here.

This is trying to download from flathub.

**Comment by losuler** [comment]
This happens whenever there's a new update (which there was only a few hours ago), because Guilded just replace the `.deb`, so the checksum fails on the new one. There's nothing I can do about this, other than automatically merging new releases without testing them.

**Comment by pogman9000** [comment]
I see. Alright, so it's better to just wait then. I don't think flatpak has a flag to append installs with to bypass checksum verification either unless I read the documentation wrong. Thanks for the feedback.

**Comment by losuler** [comment]
Just giving an update to say it looks like the latest release is broken[^1]. As this is occurring with the `.deb` release as well, I believe it's an issue on Guilded's end.

[^1]: https://github.com/flathub/gg.guilded.Guilded/pull/25#issuecomment-1462593919

**Comment by losuler** [comment]
Two weeks later and they've finally fixed this issue now (I checked it was working for me too). I've just pushed their new release https://github.com/flathub/gg.guilded.Guilded/pull/27 and it should be up on Flathub soon.
