### ISSUE TITLE
Icon is broken on flathub website

### ISSUE THREAD

**Issue by razzeee** [flathub/gg.guilded.Guilded#33]
This should either not use the `remote` icon or install the icon in the flatpak itself. 

That way it should show up fine then.

**Comment by losuler** [comment]
Tracking this under https://github.com/flathub/website/issues/1479. It was working previously, so I assume it's an issue on their end.

**Comment by razzeee** [comment]
It's actually a security/performance measure, to disallow loading images outside of our infra.

**Comment by losuler** [comment]
See my reply https://github.com/flathub/website/issues/1479. Probably best to comment over there, if you know more about this.

**Comment by losuler** [comment]
Fixed it, see my comment https://github.com/flathub/website/issues/1479#issuecomment-1547538404. Thanks again!
