### ISSUE TITLE
Sys tray icon not popping up

### ISSUE THREAD

**Issue by tjaynl** [flathub/gg.guilded.Guilded#5]
First of thanks for making this app available on flathub. But i have an issue with the systray icon not showing up, is there a way to fix it?

**Comment by losuler** [comment]
It's a known issue on Linux and hasn't been fixed yet sadly. It's not unique to the Flatpak release.

**Comment by tjaynl** [comment]
Seems weird to me that its a Linux issue since other flatpaks like Steam, Discord and other apps just work and give me the icons in the sys tray, i wonder what the issue could be then.

**Comment by losuler** [comment]
It's an issue with Guilded itself. You can verify this by downloading the `.deb` and installing or extracting and running it.

**Comment by tjaynl** [comment]
ah oke i understand now, thanks for explaining, hopefully it will get fixed soon. Thank you for the replies.

**Comment by losuler** [comment]
No worries. I'll leave this issue open so I can mark it resolved when Guilded eventually fixes the issue.

**Comment by losuler** [comment]
Great news! It seems with the release that just came out, that they've fixed the tray icons issue!

I've pushed this update and it should be available on Flathub in the next few hours.
