### ISSUE TITLE
I'm getting this error once again

### ISSUE THREAD

**Issue by RFLEpicGamer** [flathub/gg.guilded.Guilded#53]
i get `error: Failed to install gg.guilded.Guilded: Wrong size for extra data https://www.guilded.gg/downloads/Guilded-Linux.deb` when i try to run flatpak install guilded

**Comment by losuler** [comment]
Unfortunately Guilded don't keep around old versions, so the moment there's a new release this happens. I don't believe this is a normal practice, which is frustrating. I've merged the update now, so it should be up soon.
